version: "3"

services:
  plandstu-go:
    image: c0dys/plandstu-go:latest
    environment:
      - CONFIG_PATH=/app/config/local.yaml
    ports:
      - "8080:8080"
    networks:
      - plandstu
    depends_on:
      - parser
      - llm-service

  mongo-parser:
    image: mongo:latest
    container_name: mongo-parser
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/dbS
    networks:
      - plandstu
  parser:
    image: c0dys/plandstu_parser:latest
    ports:
      - "8082:8082"
    networks:
      - plandstu
    depends_on:
      - mongo-parser

  ollama-dstu:
    image: ollama/ollama
    ports:
      - 11434:11434/tcp
    networks:
      - plandstu
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - plandstu
  llm-service:
    image: c0dys/llm-dstu:latest
    ports:
      - "8085:8085"
    environment:
      - REDIS_URL=redis://redis:6379
      - OLLAMA_URL=http://ollama-dstu:11434
      - PLANDSTU-GO_URL=http://plandstu-go:8080/api/v1/llm/
      - THRESHOLD=5
    depends_on:
      - ollama-dstu
      - redis
    networks:
      - plandstu
volumes:
  mongo_data:

networks:
  plandstu:
    driver: bridge
